name: Take Screenshot of Webpage

on:
  schedule:
    - cron: '0 21 * * *'
  workflow_dispatch:

jobs:
  screenshot:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      run: |
        npm install puppeteer

    - name: Take Screenshot
      run: |
        node -e "
          const puppeteer = require('puppeteer');
          (async () => {
            const browser = await puppeteer.launch({
              args: ['--no-sandbox', '--disable-setuid-sandbox']
            });
            const page = await browser.newPage();
            await page.setViewport({ width: 1448, height: 1072 });
            await page.goto(process.env.WEBPAGE_URL);
            await page.screenshot({ path: 'wallpaper.png' });
            await browser.close();
          })();
        "
      env:
        WEBPAGE_URL: ${{ secrets.WEBPAGE_URL }}

    - name: Commit and push the screenshot
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "github-actions@users.noreply.github.com"
        git add wallpaper.png
        git commit -m "Add wallpaper screenshot"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
