name: Take Screenshot of Webpage

on:
  schedule:
    - cron: '0 21 * * *'
  workflow_dispatch:

jobs:
  screenshot:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Git configuration
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "github-actions@users.noreply.github.com"

    - name: Fetch latest changes from remote
      run: |
        git fetch origin

    - name: Create and switch to gh-pages branch (if it doesn't exist)
      run: |
        git checkout gh-pages

    - name: Pull changes
      run: |
        git pull

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      run: |
        npm install puppeteer

    - name: Take Screenshot
      run: |
        node -e "
          const puppeteer = require('puppeteer');
          const delay = ms => new Promise(resolve => setTimeout(resolve, ms));
          (async () => {
            const browser = await puppeteer.launch({
              args: ['--no-sandbox', '--disable-setuid-sandbox'],
              headless: true
            });
            const page = await browser.newPage();
            await page.setViewport({ height: 1448, width: 1072 });
            await page.goto(process.env.WEBPAGE_URL, { waitUntil: 'networkidle2' });
            await page.evaluate(() => {
              const dateElement = document.getElementById('date');
              if (dateElement) {
                dateElement.remove();
              }
            });
            await delay(5000);
            await page.screenshot({ path: 'wallpaper.png' });
            await browser.close();
          })();
        "
      env:
        WEBPAGE_URL: ${{ secrets.WEBPAGE_URL }}

    - name: Commit and push the screenshot
      run: |
        git add wallpaper.png
        git commit -m "Add wallpaper"
        git push origin gh-pages
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
